<?php
include('header.php');
?>
<h4 style="margin-left:100px;">Terms And Condition</h4>
<hr>
<body style="background-color:#E5E4E2;">
<p style="font-size:14px; margin-left:100px; margin-right:80px; color:black;">
This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder, as applicable and the amended provisions pertaining to electronic 
records in various statutes, as amended from time to time by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require 
any physical or digital signatures.<br><br>

This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that requires publishing of the rules and regulations, privacy policy and Terms of Use for access or usage of www.pharmeasy.in website and its mobile applications.
<br><br>
1.<b> GENERAL</b><br>
www.pharmeasy.in, an internet based portal and “PharmEasy”, a mobile application, (hereinafter together be referred to as “Website") is run, operated and maintained by Axelia Solutions Private Limited (hereinafter to be referred as “Company” or “We” or “Our” or “Us”), a company duly incorporated under the provisions of the Companies Act, 2013. Having its registered address at 301-B Wing, Raheja Plaza 1, Opposite R-City Mall, LBS Marg, Ghatkopar West, Mumbai 400086

Use of the Website is offered to You, subject to acceptance of all the terms, conditions and notices contained in these Terms including applicable policies which are incorporated herein by reference, along with any amendments / modifications made time to time by Company at its sole discretion and posted on the Website, including by way of imposing an additional charge for access to or use of a service(s).

For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Account Information (defined below) while registering on the Website as a registered User using the computer systems.

Company shall not be required to notify You, whether as a registered user or not, of any changes made to the Terms and Conditions ("Terms"). The revised Terms shall be made available on the Website. Your use of the Website and the Services is subject to the most current version of the Terms made available on the Website, at the time of such use. You are requested to regularly visit the Website to view the most current Terms. It shall be Your responsibility to check the Terms periodically for changes. Company may require You to provide Your consent to the updated Terms in a specified manner prior to any further use of the Website and the Services, provided on the Website. If no such separate consent is sought, Your continued use of the Website, following changes to the Terms, will constitute your express acceptance of those changes.
<br><br>

<b>2. PRODUCTS AND SERVICES</b><br>
The Website is a platform that facilitates, as an intermediary, the online requisition by the user for purchase of medicines and wellness / health related products and services offered by Company's various registered third-party/ies (third-parties shall for the purpose of this Terms, include without limitation, third party retail pharmacies, third-party labs et al) ("Products and Services"). The sale & purchase / transaction between the registered third-parties and You, of Products and Services, facilitated by the requisition placed by You on the Website shall be governed by these Terms. Company is not and cannot be a party to or save as except as may be provided in these Terms of Use, control in any manner, any transaction between You and the third-parties.
Company further reserves the right to change or modify these Terms of Use or any policy or guidelines of the Website including the Privacy Policy, at any time and in its sole discretion. Any changes or modifications made will be effective immediately upon posting the revisions on the Website and You waive any right You may have to receive specific notice of such changes or modifications. Your continued use of the Website will confirm Your acceptance of such changes or modifications.
Technology Platform for Pharmaceutical Products –<br>
Company facilitates the purchase of drugs and other pharmaceutical products, nutraceutical products and services (which shall also include Over The Counter (OTC) and wellness products) offered by third-party retail pharmacies (“Retail Pharmacies”). The Company and the Website merely provide hosting and technology intermediary services to You and persons browsing/ visiting the Website. All items offered for sale on the Website, and the content made available by the Retail Pharmacies, are third party user generated contents and third party products. The Company has no control over such third party user generated contents and/ Pharmaceutical Goods and Services and does not originate or initiate the transmission, or select the sender/recipient of the transmission, or the information contained in such transmission. The authenticity and genuineness of the Pharmaceutical Goods and Services made available by the Retail Pharmacies through the Website shall be the sole responsibility of the Retail Pharmacies. The Company shall have no liability with respect to the authenticity of the Pharmaceutical Goods and Services being facilitated through the Website.
</p>
</body>
<?php
include('footer.php');
?>